### ISSUE TITLE
Question: are portal blocks meant to actually portal you into the next dimension ?

### ISSUE THREAD

**Issue by Zygus42** [CD4017BE/VerticallyStackedDimensions#19]
The reason I ask is that as you can see in the picture below, I'm standing on the portal blocks and they're doing nothing.

![2019-08-02_16 53 41](https://user-images.githubusercontent.com/20757445/62358681-c1308a00-b547-11e9-904f-75f5bde75100.png)

 I also can't break them or interact with them in any way (in Survival mode).  I can break them in Creative mode, and then it portals me to the next dimension when i jump into the resulting void.

VerticalDimensionStack-1.12.2-0.1.4
CD4017BE_lib-1.12.2-6.4.6
forge-1.12.2-14.23.5.2838-installer-win

**Comment by CD4017BE** [comment]
Yes the portals only teleport you when they're open, see [documenation](https://github.com/CD4017BE/VerticallyStackedDimensions/wiki/Transition-Portal#behavior).

The reason you were unable to break them in survival is probably because there is an unbreakable block like bedrock on the other side.
I see bedrock blocks in your screenshot so you probably forgot to configure the dimension settings so that the mod prevents the generation of bedrock blocks in these dimensions.

**Comment by Zygus42** [comment]
Was wondering if the issue was bedrock.  I have this in the config:
	!prevent bedrock from being generated in ...
	rem_block_gen:0 = "minecraft:bedrock"; !the Overworld
	rem_block_gen:-1 = "minecraft:bedrock"; !the Nether

I'm guessing one of the other mods is spawning in bedrock after your mod removes it ?  Been trying to figure out which mod is doing it, but no luck so far.

**Comment by Zygus42** [comment]
Turns out to be Realistic Terrain Gen.  I turned the bedrock depth down to 1 block (the minimum) and I get this:
![2019-08-06_03 12 30](https://user-images.githubusercontent.com/20757445/62488984-332efa80-b7f8-11e9-9d0c-4c163e98cbe9.png)

So there are spots where you can break through and ones you can't.  Not ideal, but workable.

I would have thought that you would get ported by standing on the portal blocks........

**Comment by CD4017BE** [comment]
By the way there is also a [second method of removing bedrock](https://github.com/CD4017BE/VerticallyStackedDimensions/wiki/Bedrock-Removal#block-replacement) that runs a bit later in the world generation procedure. Maybe that can kill the late generated bedrock from Realistic Terrain Gen.
