### ISSUE TITLE
Not able to remove Advent of Ascension "bedrock"

### ISSUE THREAD

**Issue by sumrex** [CD4017BE/VerticallyStackedDimensions#23]
Certain Advent of Ascension dimensions spawn dimensional fabric instead of bedrock. I am unable to prevent this from spawning for some reason despite the configuration settings.

I have the dimensions stacked up, and rem_block_gen:807 = "aoa3:dimensional_fabric" but it does not work. I have not seen any errors in the logs about the script.

## Used versions
Minecraft-1.12.2
VerticallyStackedDimensions-1.12.2-0.1.5
CD4017BE_lib-1.12.2-6.4.13
Forge-14.23.5.2847
Advent of Ascension 3.1.2.b

**Comment by jelaw21** [comment]
Have you tried setting the height of the portal to 1 y-level below the dimensional fabric?

**Comment by jelaw21** [comment]
I was able to accomplish this by putting the rem_block_gen:807 = "aoa3:dimensional_fabric"  in the INIT() instead of the PRE_INIT(), so it removes the block AFTER the dim is created.

**Comment by CD4017BE** [comment]
`INIT()` and `PRE_INIT()` are related mod loading phases and have nothing to do with world generation. Where you put stuff in the config only matters for things that depend on content from other mods already being loaded or when providing content (ex. OreDictionary entries) that other mods may depend on during loading.

But it's possible that the dimensional fabric block just hadn't been registered at pre init. So I should probably better store those block ids as String values and only actually parse them into BlockStates later when they are used for world generation.
