### ISSUE TITLE
Crash, Not sure how ...

### ISSUE THREAD

**Issue by jelaw21** [CD4017BE/VerticallyStackedDimensions#30]
## What happened
One of my players was testing a dupe theory about throwing an item into the transistion layer and getting a second one on the other side. 
## What I did
That is all I know.
## Used versions
Minecraft-1.12.2
VerticallyStackedDimensions-1.12.2-0.1.7.2.
CD4017BE_lib-1.12.2-6.4.17.1.
Forge-14.23.5.2847
other installed mods _(only relevant ones, like those providing dimensions to your dimension stacks or modifying terrain generation)_
Advent of Ascension

Crash Log:
[crash-2020-03-13_21.39.42-server.txt](https://github.com/CD4017BE/VerticallyStackedDimensions/files/4332179/crash-2020-03-13_21.39.42-server.txt)

**Comment by CD4017BE** [comment]
The new release should fix the crash issue.

And just in case you actually manage to find a working item duplication glitch, I would be very interested to know about it.
