### ISSUE TITLE
Can't destroy transition portal on survival mode.

### ISSUE THREAD

**Issue by hasuu** [CD4017BE/VerticallyStackedDimensions#31]
What should i do? any config or smth?

**Comment by CD4017BE** [comment]
There is probably Bedrock on the other side that wasn't removed from world gen.

**Comment by hasuu** [comment]
How can i make it work again then? Please playin with friends already with 10h in world.

**Comment by CD4017BE** [comment]
The bedrock removal features from the mod itself unfortunately only work when freshly generating a new world.

So the only thing you can do at this stage is to go into creative mode and remove the bedrock manually or use a command like `/fill ~-64 1 ~-64 ~63 4 ~63 minecraft:stone replace minecraft:bedrock` (change the y values 1 and 4 to the actual heights where the bedrock is).

**Comment by hasuu** [comment]
I generated it on SMP then added it on MPP but when i removed bedrock in nether. Nether was broken. So do i type this commmand in overworld or nether?

**Comment by CD4017BE** [comment]
`/fill ~-64 1 ~-64 ~63 4 ~63 minecraft:stone replace minecraft:bedrock` would be for overworld.
`/fill ~-64 123 ~-64 ~63 126 ~63 minecraft:netherrack replace minecraft:bedrock` would be for nether ceiling.

These are basically vanilla block fill commands that replace all bedrock blocks in a certain height range with stone / netherrack within a 64 block radius around the player.

I'm now working on retroactive bedrock removal and adding more efficient commands for these kind of things.

**Comment by hasuu** [comment]
'replace' is not a state for block minecraft:stone is what it gives me when i type the command

**Comment by CD4017BE** [comment]
I've implemented the retro-gen command now in v0.1.9 and wrote a small tutorial for it in the [wiki](https://github.com/CD4017BE/VerticallyStackedDimensions/wiki/Adding-the-mod-to-existing-worlds).
